---
- name: Apply Password Policy on Ubuntu Servers
  hosts: uat_servers
  become: yes
  tasks:
    - name: Install libpam-pwquality if not present
      apt:
        name: libpam-pwquality
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure password quality requirements
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^(#)?(minlen|maxrepeat|maxclassrepeat|dcredit|ucredit|lcredit|ocredit|dictpath|enforce-for-root)="
        line: "{{ item }}"
      loop:
        - "minlen = 12"
        - "maxrepeat = 3"
        - "maxclassrepeat = 2"
        - "dcredit = -1"
        - "ucredit = -1"
        - "lcredit = -1"
        - "ocredit = -1"

    - name: Ensure password expiration settings
      lineinfile:
        path: /etc/login.defs
        regexp: "^{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
      loop:
        - { key: "PASS_MAX_DAYS", value: "90" }
        - { key: "PASS_MIN_DAYS", value: "7" }
        - { key: "PASS_WARN_AGE", value: "14" }

    - name: Ensure password policy is enforced
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+required\s+pam_pwquality.so'
        line: "password required pam_pwquality.so retry=3"
